### ISSUE TITLE
Heroku Pushes fail when referencing this package

### ISSUE THREAD

**Issue by charliepfm** [heroku-softtrends/heroku-php-sqlsrv-buildpack#1]
When trying to push to Heroku, if fails. According to Heroku support the problem lies within this package.

Part of the error message is posted below:

       
         Problem 1
           - Root composer.json requires PHP extension ext-sqlsrv ^5.10 but it is missing from your system. Install or enable PHP's sqlsrv extension.
         Problem 2
           - Root composer.json requires PHP extension ext-pdo_sqlsrv ^5.10 but it is missing from your system. Install or enable PHP's pdo_sqlsrv extension.
       
       To enable extensions, verify that they are enabled in your .ini files:
           - /app/.heroku/php/etc/php/php.ini
           - /app/.heroku/php/etc/php/conf.d/000-heroku.ini
           - /app/.heroku/php/etc/php/conf.d/010-ext-zend_opcache.ini
           - /app/.heroku/php/etc/php/conf.d/100-ext-sqlsrv.ini
           - /app/.heroku/php/etc/php/conf.d/110-ext-soap.ini
           - /app/.heroku/php/etc/php/conf.d/120-ext-pdo_sqlsrv.ini
           - /tmp/codon/tmp/buildpacks/924b28589fd8017df2c94cc0b5722165fa7a91ef/conf/php/apm-nostart-overrides/apm-nostart-overrides.ini
       You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
       Alternatively, you can run Composer with `--ignore-platform-req=ext-sqlsrv --ignore-platform-req=ext-pdo_sqlsrv` to temporarily ignore these required extensions.
[1;31m
 !     ERROR: Dependency installation failed!
 !     
 !     The 'composer install' process failed with an error. The cause
 !     may be the download or installation of packages, or a pre- or
 !     post-install hook (e.g. a 'post-install-cmd' item in 'scripts')
 !     in your 'composer.json'.
 !     
 !     Typical error cases are out-of-date or missing parts of code,
 !     timeouts when making external connections, or memory limits.
 !     
 !     Check the above error output closely to determine the cause of
 !     the problem, ensure the code you're pushing is functioning
 !     properly, and that all local changes are committed correctly.
 !     
 !     For more information on builds for PHP on Heroku, refer to
 !     https://devcenter.heroku.com/articles/php-support
[0m
 !     Push rejected, failed to compile PHP app.

**Comment by heroku-softtrends** [comment]
Share your heroku app configvar(**HEROKU_PHP_PLATFORM_REPOSITORIES**) value and php version used.

**Comment by charliepfm** [comment]
PHP version
8.1.12

HEROKU_PHP_PLATFORM....
https://raw.githubusercontent.com/heroku-softtrends/mssql-server-drivers-for-php/main/5.10.0/ubuntu/20.04/php/8.1/nts/packages.json

**Comment by charliepfm** [comment]
Update - Heroku Support states we are running on PHP version 8.2.

**Comment by heroku-softtrends** [comment]
{
    "require": {
      "php": "~8.1.0",
      "ext-sqlsrv": "^5.10",
      "ext-pdo_sqlsrv": "^5.10"
    }
}

**Comment by heroku-softtrends** [comment]
set your PHP version like "~8.1.0" in composer.json and not like "^8.1.0".

**Comment by charliepfm** [comment]
That did it. thank you very much. Sorry about all the chaff noise in tracking this down.
